name: Vue Deployment

on:
  push:
    branches: [main]

jobs:
  kubernetes:
    name: Deploy to kubernetes
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ vars.DOCKER_IMAGE }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_IMAGE }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Substitute image tag
        id: ingress-var-substitution
        uses: datamonsters/replace-action@v2
        with:
          files: "ops/kubernetes/deployment.yaml"
          replacements: "$$IMAGE_TAG$$=${{ github.sha }}"

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.CLUSTER_TOKEN }}
          clusterName: ${{ vars.CLUSTER_NAME }}

      - name: Deploy kustomization
        run: kubectl apply -k ops/kubernetes

      - name: Wait for service to deploy
        run: kubectl rollout status deployment/${{ vars.DEPLOYMENT_NAME }}
